!Webb/MvcProjeKampi/Controllers/WriterMessageController.cs
using BusinessLayer.Concreate;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFrameWork;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayer.Concreate;
using EntityLayer.Concreate;
using ValidationResult = FluentValidation.Results.ValidationResult;
using PagedList;
using PagedList.Mvc;

namespace MvcProjeKampi.Controllers
{
    [Authorize]
    public class WriterMessageController : Controller
    {
        private MessageMenager mm = new MessageMenager(new EfMessageDal());
        private ContactMenager cm = new ContactMenager(new EfContactDal());


        //gönderen kişiyi session at 




        public ActionResult Inbox(string s,string yazi = "",int ses=0,int p=1)
        {
            if (ses==1)
            {
                yazi = "";
                Context c = new Context();
                s = (string)Session["WriterMail"];
                var messagelist = mm.GetListSearch(yazi,s).ToPagedList(p,10);
                return View(messagelist);
            }
            else
            {
                Context c = new Context();
                s = (string)Session["WriterMail"];
                var messagelist = mm.GetListSearch(yazi,s).ToPagedList(p,10);
                return View(messagelist);
            }
            
        }

        public PartialViewResult MessageMenu()
        {
            string mail = (string)Session["WriterMail"];
            ViewBag.Message = mm.GetListInbox(mail).Count(x => x.MessageInboxIsRead == false&&x.MessageDraftStatus==false&&x.MessageStatus==true);
            return PartialView();
        }
        public ActionResult Sendbox(string s, string yazi = "", int ses = 0,int p = 1)
        {
            if (ses == 1)
            {
                yazi = "";
                Context c = new Context();
                s = (string)Session["WriterMail"];
                var messagelist = mm.GetListSendBoxSearch(s,yazi).Where(x => x.MessageStatus == true && x.MessageDraftStatus == false).ToList().ToPagedList(p,10);
                return View(messagelist);
            }
            else
            {
                Context c = new Context();
                s = (string)Session["WriterMail"];
                var messagelist = mm.GetListSendBoxSearch(s,yazi).Where(x => x.MessageStatus == true && x.MessageDraftStatus == false).ToList().ToPagedList(p,10);
                return View(messagelist);
            }
            
        }

        //Yeni Mesaj
        [HttpGet]
        public ActionResult AddNewMessage()
        {
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddNewMessage(Message p, string parameter)
        {
            MessageValidator mv = new MessageValidator();
            ValidationResult vr = mv.Validate(p);
            if (vr.IsValid)
            {
                if (parameter == "send")
                {
                    p.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    p.MessageSenderMail = (string)Session["WriterMail"];
                    p.MessageDraftStatus = false;
                    p.MessageStatus = true;
                    mm.MessageAdd(p);
                    return RedirectToAction("Sendbox");
                }

                if (parameter == "draft")
                {
                    p.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    p.MessageSenderMail = (string)Session["WriterMail"];
                    p.MessageDraftStatus = true;
                    p.MessageStatus = true;
                    mm.MessageAdd(p);
                    return RedirectToAction("MessageDraftMenu");
                }
            }
            else
            {
                foreach (var item in vr.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        //Taslak Görüntüleme Sayfası
        public ActionResult MessageDraftMenu(string s, string yazi = "", int ses = 0, int p = 1)
        {
            if (ses == 1)
            {
                yazi = "";
                Context c = new Context();
                s = (string)Session["WriterMail"];
                var messagelist = mm.GetListSendBoxSearch(s, yazi).Where(x => x.MessageDraftStatus == true && x.MessageStatus == true).ToList().ToPagedList(p, 10);
                return View(messagelist);
            }
            else
            {
                Context c = new Context();
                s = (string)Session["WriterMail"];
                var messagelist = mm.GetListSendBoxSearch(s,yazi).Where(x => x.MessageDraftStatus == true && x.MessageStatus == true).ToList().ToPagedList(p, 10);
                return View(messagelist);
            }
            
        }
        //Mesaj Detayları
        public ActionResult GetInboxMessageDetails(int id)
        {
            var messagelist = mm.GetById(id);
            messagelist.MessageInboxIsRead = true;
            mm.MessageUpdate(messagelist);
            return View(messagelist);
        }

        //Gönderilen Mesaj Detayları
        public ActionResult GetSendBoxMessageDetails(int id)
        {
            var messagelist = mm.GetById(id);
            return View(messagelist);
        }
        //Taslak GÖnderme
        [HttpGet]
        public ActionResult MessageSendDraft(int id)
        {
            var messagelist = mm.GetById(id);
            return View(messagelist);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult MessageSendDraft(Message p, string parameter)
        {
            MessageValidator mv = new MessageValidator();
            ValidationResult vr = mv.Validate(p);
            if (vr.IsValid)
            {
                if (parameter == "send")
                {
                    p.MessageDate = DateTime.Parse(DateTime.Now.ToShortDateString());
                    p.MessageSenderMail = (string)Session["WriterMail"];
                    p.MessageDraftStatus = false;
                    p.MessageStatus = true;
                    mm.MessageUpdate(p);
                    return RedirectToAction("Sendbox");
                }
            }
            else
            {
                foreach (var item in vr.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        //çöp kutusu
        public ActionResult DeleteBoxResult(string s, string yazi = "", int ses = 0, int p = 1)
        {
            if (ses == 1)
            {
                yazi = "";
                Context c = new Context();
                s = (string)Session["WriterMail"];
                ViewBag.usermail = s;
                var messagelist = mm.GetListDeleteBoxSearch(s, yazi).ToPagedList(p, 10);
                return View(messagelist);
            }
            else
            {
                Context c = new Context();
                s = (string)Session["WriterMail"];
                ViewBag.usermail = s;
                var messagelist = mm.GetListDeleteBoxSearch(s, yazi).Where(x => x.MessageStatus == false && x.MessageDraftStatus == false).ToList().ToPagedList(p, 10);
                return View(messagelist);
            }
        }

        [HttpPost]
        public ActionResult DeleteDrafts(int[] selectedDrafts)
        {
            foreach (int id in selectedDrafts)
            {
                var deletedraft = mm.GetById(id);
                deletedraft.MessageDraftStatus = false;
                deletedraft.MessageStatus = false;
                mm.MessageUpdate(deletedraft);
            }
            return Json(new { success = true });
        }
        [HttpPost]
        public ActionResult DeleteDraftsEnd(int[] selectedDrafts)
        {
            foreach (int id in selectedDrafts)
            {
                var deletedraft = mm.GetById(id);
                deletedraft.MessageDraftStatus = false;
                deletedraft.MessageStatus = false;
                deletedraft.MessageDeleteStatus = true;
                mm.MessageUpdate(deletedraft);
            }
            return Json(new { success = true });
        }
    }
}

!Webb/MvcProjeKampi/Views/WriterMessage/AddNewMessage.cshtml
@model EntityLayer.Concreate.Message
@{
    ViewBag.Title = "AddNewMessage";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Yeni Mesaj Sayfası</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    <div class="card">
                        @Html.Action("MessageMenu", "WriterMessage")
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                    <!-- /.card -->
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    @using (Html.BeginForm("AddNewMessage", "WriterMessage"))
                    {
                        <div class="card card-primary card-outline">
                            <div class="card-header">
                                <h3 class="card-title">Yeni Mesaj Oluştur</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.MessageReceiverMail, new { @class = "form-control", @placeholder = "Alıcı:" })
                                    <font color="red">@Html.ValidationMessageFor(x => x.MessageReceiverMail)</font>
                                </div>
                                <div class="form-group">
                                    @Html.TextBoxFor(x => x.MessageSubject, new { @class = "form-control", @placeholder = "Konu:" })
                                    <font color="red">@Html.ValidationMessageFor(x => x.MessageSubject)</font>
                                </div>
                                <div class="form-group">
                                    @Html.Label("Mesajınız:")
                                    @Html.TextAreaFor(x => x.MessageContent, new { id = "compose-textarea", @class = "form-control", @style = "height: 300px" })

                                    <font color="red"> @Html.ValidationMessageFor(x => x.MessageContent)</font>

                                </div>
                                <div class="form-group">
                                    <div class="btn btn-default btn-file">
                                        <i class="fas fa-paperclip"></i> Dosya Ekle
                                        <input type="file" name="attachment">
                                    </div>
                                    <p class="help-block">Max. 32MB</p>
                                </div>
                            </div>
                            <!-- /.card-body -->
                            <div class="card-footer">
                                <div class="float-right">
                                    <button type="submit" name="parameter" value="draft" class="btn btn-default"><i class="fas fa-pencil-alt"></i> Taslaklara Kaydet</button>
                                    <button type="submit" name="parameter" value="send" class="btn btn-primary"><i class="far fa-envelope"></i> Gönder</button>
                                </div>
                                <button type="reset" class="btn btn-default"><i class="fas fa-times"></i> İptal Et</button>
                            </div>
                            <!-- /.card-footer -->
                        </div>
                    }
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    @section Scripts
    {
        <!-- Bootstrap 4 -->
        <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
        <!-- AdminLTE App -->
        <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
        <!-- Summernote -->
        <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
        <!-- Page Script -->
        <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
        })</script>
    }
</body>
</html>

!Webb/MvcProjeKampi/Views/WriterMessage/DeleteBoxResult.cshtml
@using EntityLayer.Concreate
@model PagedList.IPagedList<Message>
@using PagedList
@using PagedList.Mvc
@{
    ViewBag.Title = "DeleteBoxResult";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/butoncssleri/aramabutonu.css" type="text/css" />
</head>
<body class="hold-transition sidebar-mini">

    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Çöp Kutusu</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-3">

                @Html.Action("MessageMenu", "WriterMessage")
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Silinen Mesajlar</h3>
                        <div class="card-tools">
                            <form method="post" action="/WriterMessage/DeleteBoxResult">
                                <div class="input-group input-group-sm">

                                    <input type="text" class="form-control" name="yazi" placeholder="Çöp Kutusunda Ara">

                                    <div class="input-group-append">
                                        <button class="my-button">
                                            <i class="fa fa-search" style="color: white; margin-right: 10px;"></i>
                                        </button>
                                    </div>
                                    <div class="input-group-append">
                                        <button class="my-button" name="ses" value="1">
                                            <i class="nav-icon fas fa-bars" style="color: white; margin-right: 10px;"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <!-- /.card-tools -->
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <label style="text-align: center; margin: auto; " class="btn btn-primary btn-sm checkbox-toggle">
                                <input type="checkbox" id="select-all">
                            </label>
                            <div class="btn-group">
                                <button type="button" onclick="deleteSelectedDrafts()" class="btn btn-primary btn-sm"><i class="far fa-trash-alt"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" onclick="location.reload()" class="btn btn-primary btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                <div class="btn-group">
                                    @Html.PagedListPager((IPagedList)Model, page => Url.Action("DeleteBoxResult", new { p = page }), new PagedListRenderOptions()
                                    {
                                        LiElementClasses = new List<string>() { "page-item" },
                                        UlElementClasses = new List<string>() { "pagination" },
                                        ContainerDivClasses = new List<string>() { "btn-group" },
                                        LinkToPreviousPageFormat = "<button type='button' class='btn btn-sm btn-primary border rounded-circle'><i class='fas fa-chevron-left'></i></button>",
                                        LinkToNextPageFormat = "<button type='button' class='btn btn-sm btn-primary border rounded-circle'><i class='fas fa-chevron-right'></i></button>",
                                        DisplayPageCountAndCurrentLocation = false,
                                        DisplayLinkToFirstPage = PagedListDisplayMode.Never,
                                        DisplayLinkToLastPage = PagedListDisplayMode.Never,
                                        LinkToIndividualPageFormat = "",
                                        PageCountAndCurrentLocationFormat = ""
                                    })
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                        <div class="table-responsive mailbox-messages">
                            <table class="table table-hover table-striped">
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                <div class="icheck-primary">
                                                    <input type="checkbox" class="my-checkbox" name="my-checkbox" value="@item.MessageID">
                                                    <label for="check_@item.MessageID" hidden="true">@item.MessageID</label>
                                                </div>

                                                <script>
                                                    $(document).ready(function () {
                                                        $('#select-all').click(function () {
                                                            if ($(this).prop('checked')) {
                                                                $('.my-checkbox').prop('checked', true);
                                                            } else {
                                                                $('.my-checkbox').prop('checked', false);
                                                            }
                                                        });
                                                    });
                                                </script>
                                            </td>
                                            @if (ViewBag.usermail == item.MessageReceiverMail)
                                            {

                                                <td><button type="button" class="btn btn-outline-danger btn-sm">Alındı</button></td>
                                                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                                <!--buraya alınmış mailse bişey ekle-->
                                                <td class="mailbox-name"><a href="/WriterMessage/GetSendBoxMessageDetails/@item.MessageID">@item.MessageSenderMail</a></td>
                                            }
                                            else
                                            {
                                                <td><button type="button" class="btn btn-outline-success btn-sm">Gönderildi</button></td>
                                                <td class="mailbox-star"><a href="#"><i class="fas fa-star text-warning"></i></a></td>
                                                <!--buraya alınmış mailse bişey ekle-->
                                                <td class="mailbox-name"><a href="/WriterMessage/GetSendBoxMessageDetails/@item.MessageID">@item.MessageReceiverMail</a></td>
                                            }

                                            <td class="mailbox-subject">
                                                <b>@item.MessageSubject</b>
                                            </td>
                                            <td class="mailbox-attachment"></td>
                                            <td class="mailbox-date">@(((DateTime)item.MessageDate).ToString("dd-MMM-yyyy"))</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.mail-box-messages -->
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-0">
                        <div class="mailbox-controls">
                            <!-- Check all button -->
                            <div class="btn-group">
                                <button type="button" onclick="deleteSelectedDrafts()" class="btn btn-primary btn-sm"><i class="far fa-trash-alt"></i></button>
                            </div>
                            <!-- /.btn-group -->
                            <button type="button" onclick="location.reload()" class="btn btn-primary btn-sm"><i class="fas fa-sync-alt"></i></button>
                            <div class="float-right">
                                <div class="btn-group">
                                    @Html.PagedListPager((IPagedList)Model, page => Url.Action("DeleteBoxResult", new { p = page }), new PagedListRenderOptions()
                                    {
                                        LiElementClasses = new List<string>() { "page-item" },
                                        UlElementClasses = new List<string>() { "pagination" },
                                        ContainerDivClasses = new List<string>() { "btn-group" },
                                        LinkToPreviousPageFormat = "<button type='button' class='btn btn-sm btn-primary border rounded-circle'><i class='fas fa-chevron-left'></i></button>",
                                        LinkToNextPageFormat = "<button type='button' class='btn btn-sm btn-primary border rounded-circle'><i class='fas fa-chevron-right'></i></button>",
                                        DisplayPageCountAndCurrentLocation = false,
                                        DisplayLinkToFirstPage = PagedListDisplayMode.Never,
                                        DisplayLinkToLastPage = PagedListDisplayMode.Never,
                                        LinkToIndividualPageFormat = "",
                                        PageCountAndCurrentLocationFormat = ""
                                    })
                                </div>
                                <!-- /.btn-group -->
                            </div>
                            <!-- /.float-right -->
                        </div>
                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <script>
        function deleteSelectedDrafts() {
            var selectedDrafts = [];
            $('.my-checkbox:checked').each(function () {
                selectedDrafts.push($(this).val());
            });
            if (selectedDrafts.length > 0) {
                $.ajax({
                    type: 'POST',
                    url: '/WriterMessage/DeleteDraftsEnd',
                    data: { selectedDrafts: selectedDrafts },
                    success: function (result) {
                        // Silme işlemi başarılıysa yapılacak işlemler
                        location.reload();
                    },
                    error: function (xhr, status, error) {
                        // Silme işlemi başarısız olursa yapılacak işlemler
                    }
                });
            }
        }
    </script>
</body>
</html>

!Webb/MvcProjeKampi/Views/WriterMessage/GetInboxMessageDetails.cshtml
@model EntityLayer.Concreate.Message
@{
    ViewBag.Title = "GetInboxMessageDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Detayı</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    @Html.Action("MessageMenu", "WriterMessage")
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu: @Html.DisplayFor(x => x.MessageSubject)</h5>
                                <h6>
                                    Mail: @Html.DisplayFor(x => x.MessageSenderMail)
                                    <span class="mailbox-read-time float-right"> @DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToString("dd-MMM-yyyy")</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>Mesaj:</p>
                                <p>@Html.Raw(Model.MessageContent)</p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>

                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
        </div>   <!-- /.row -->
    </section>
</body>
</html>

!Webb/MvcProjeKampi/Views/WriterMessage/GetSendBoxMessageDetails.cshtml
@model EntityLayer.Concreate.Message
@{
    ViewBag.Title = "GetSendBoxMessageDetails";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Mesaj Detayı</h1>
                </div>

            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    @Html.Action("MessageMenu", "WriterMessage")
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Mesajı Oku</h3>
                            <div class="card-tools">
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Previous"><i class="fas fa-chevron-left"></i></a>
                                <a href="#" class="btn btn-tool" data-toggle="tooltip" title="Next"><i class="fas fa-chevron-right"></i></a>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <div class="mailbox-read-info">
                                <h5>Konu: @Html.DisplayFor(x => x.MessageSubject)</h5>
                                <h6>
                                    Alıcı Mail: @Html.DisplayFor(x => x.MessageReceiverMail)
                                    <span class="mailbox-read-time float-right"> @DateTime.Parse(Html.DisplayFor(x => x.MessageDate).ToString()).ToString("dd-MMM-yyyy")</span>
                                </h6>
                            </div>
                            <!-- /.mailbox-read-info -->
                            <!-- /.mailbox-controls -->
                            <div class="mailbox-read-message">
                                <p>Mesaj:</p>
                                <p>@Html.Raw(Model.MessageContent)</p>
                            </div>
                            <!-- /.mailbox-read-message -->
                        </div>

                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
        </div>   <!-- /.row -->
    </section>
</body>
</html>